version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - CADDY_API_KEY=${CADDY_API_KEY}
    networks:
      - app-network
    ports:
      - "8080:80"

  caddy:
    image: caddy:2
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019" # Admin API port
    depends_on:
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
